# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  midiff_config = release

else ifeq ($(config),debug)
  midiff_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := midiff

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

midiff:
ifneq (,$(midiff_config))
	@echo "==== Building midiff ($(midiff_config)) ===="
	@${MAKE} --no-print-directory -C . -f midiff.make config=$(midiff_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f midiff.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   midiff"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"